'use strict';
(() => {
  const PLAN_KEY = 'evora-pages-private-plan-v1';
  const PROGRESS_KEY = 'evora-pages-private-progress-v1';
  const FORMAT = 'evora-pages-private-progress-v1';
  const MAX_FILE = 10 * 1024 * 1024;
  const COURSE_CODES = new Set(['INF13207L','INF13204L','INF14387L','MAT02354L','INF13186L']);
  const COMPONENTS = [['anki','anki_minutes','Anki: attempt before revealing; review due cards first in Anki'],['explanation','explanation_minutes','One relevant explanation: pause and explain from memory'],['practice','practice_minutes','Independent practice or required work: make an actual attempt'],['breaks','break_minutes','Breaks inside this session']];
  const n = Object.fromEntries(['plan-file','progress-file','export-progress','file-status','onboarding','workspace','verification','plan-notes','month','previous-month','next-month','today','month-title','calendar-days','day-title','week-total','checklist','work-note','save-status','requirements','upcoming','undated'].map(id => [id,document.getElementById(id)]));
  const dateFmt = new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
  const monthFmt = new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'});
  const campusTimeFmt = new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Lisbon'});
  const localDateFmt = new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/London'});
  let plan = null, byDate = new Map(), months = [], selected = today(), state = {days:Object.create(null)}, noteTimer;
  function today(){return localDateFmt.format(new Date());}
  function text(v){return v == null ? '' : String(v);}
  function el(tag,value,cls){const x=document.createElement(tag);if(value!==undefined)x.textContent=text(value);if(cls)x.className=cls;return x;}
  function record(v){return v !== null && typeof v === 'object' && !Array.isArray(v);}
  function validDate(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T12:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===v;}
  function dateObj(v){return new Date(v+'T12:00:00Z');}
  function addDays(v,count){const d=dateObj(v);d.setUTCDate(d.getUTCDate()+count);return d.toISOString().slice(0,10);}
  function minutes(v){return typeof v==='number'&&Number.isFinite(v)&&v>=0?v:0;}
  function array(v){return Array.isArray(v)?v:[];}
  function status(message,error=false){n['file-status'].textContent=message;n['file-status'].className='status'+(error?' error':'');}
  function safeURL(value){try{const u=new URL(text(value));if(!['https:','http:'].includes(u.protocol)||u.username||u.password)return null;const host=u.hostname.toLowerCase();if(['localhost','127.0.0.1','0.0.0.0','[::1]'].includes(host))return null;return u.href;}catch(_){return null;}}
  function sourceLink(parent,label,value){const url=safeURL(value);if(!url)return;const a=el('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';parent.append(a);}
  function helperLink(parent,label,kind,code){if(!COURSE_CODES.has(code))return;const a=el('a',label);a.href=kind==='anki'?'anki_cards.html?course='+encodeURIComponent(code)+'&track=foundation':'courses/'+encodeURIComponent(code)+'.html#video-explanations';parent.append(a);}
  function signature(task){if(!record(task))return '';return JSON.stringify([text(task.course),text(task.task),minutes(task.total_minutes),minutes(task.focus_minutes),minutes(task.break_minutes),COMPONENTS.map(([,field])=>minutes(task.components?.[field]))]);}
  function validTick(day,key,task){const s=state.days[day];return !!(s&&s[key]===true&&s[key+'Signature']===signature(task));}
  function reportedMinutes(day){let sum=0;const core=day.core;if(core&&validTick(day.date,'core',core))sum=minutes(core.total_minutes);else if(core?.components)for(const [key,field] of COMPONENTS)if(validTick(day.date,key,core))sum+=minutes(core.components[field]);if(day.optional_extra&&validTick(day.date,'extra',day.optional_extra))sum+=minutes(day.optional_extra.total_minutes);return sum;}
  function requireRange(item){const start=item.calendar_window_start||item.official_date;const end=item.calendar_window_end||item.official_window_end||item.official_date;return validDate(start)&&validDate(end)?[start,end]:null;}
  function requirements(date){return array(plan?.dated_requirements).filter(item=>{const r=requireRange(item);return r&&r[0]<=date&&r[1]>=date;});}
  function markers(date){return array(plan?.planning_markers).filter(item=>validDate(item.start_date)&&validDate(item.end_date_exclusive)&&item.start_date<=date&&item.end_date_exclusive>date);}
  function eventKind(event){const start=text(event.start),end=text(event.end),midnight=/^\d{4}-\d{2}-\d{2}T00:00:00(?:\.000)?$/;if(validDate(start)||(midnight.test(start)&&midnight.test(end)))return 'date';if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?$/.test(start))return 'floating';return 'timed';}
  function eventRange(event){const start=text(event.start),end=text(event.end),kind=eventKind(event);if(kind==='date'){const a=start.slice(0,10),b=end.slice(0,10);return validDate(a)?[a,validDate(b)?addDays(b,-1):a]:null;}if(kind==='floating'){const a=start.slice(0,10),b=end.slice(0,10);return validDate(a)?[a,validDate(b)?(end.slice(11,16)==='00:00'&&b>a?addDays(b,-1):b):a]:null;}const a=new Date(start),b=new Date(end);if(Number.isNaN(a.getTime()))return null;return [localDateFmt.format(a),Number.isNaN(b.getTime())?localDateFmt.format(a):localDateFmt.format(new Date(Math.max(a.getTime(),b.getTime()-1)))];}
  function allEvents(){const map=new Map();for(const event of [...array(plan?.calendar_events),...array(plan?.class_events),...array(plan?.other_calendar_events)]){if(!record(event))continue;const key=event.id||JSON.stringify([event.title,event.start,event.end]);if(!map.has(key))map.set(key,event);}return [...map.values()];}
  function commitments(date){return allEvents().filter(item=>{const r=eventRange(item);return r&&r[0]<=date&&r[1]>=date;});}
  function validatePlan(value){if(!record(value)||!Array.isArray(value.days)||!Array.isArray(value.weeks))throw new Error('Choose a daily-checklists.json plan with days and weeks.');if(value.days.length>3000||value.weeks.length>500)throw new Error('This plan has more dates than this viewer supports.');const seen=new Set();for(const d of value.days){if(!record(d)||!validDate(d.date)||seen.has(d.date))throw new Error('The plan contains an invalid or duplicated daily date.');seen.add(d.date);for(const task of [d.core,d.optional_extra])if(task!=null&&(!record(task)||typeof task.task!=='string'||!Number.isFinite(task.total_minutes)||task.total_minutes<0))throw new Error('A study task is missing valid text or minutes.');}for(const w of value.weeks)if(!record(w)||!validDate(w.week_start)||!validDate(w.week_end)||!Array.isArray(w.days)||w.days.some(d=>!record(d)||!validDate(d.date)))throw new Error('A weekly planning record is invalid.');return value;}
  function safeProgress(value){if(!record(value)||!record(value.days))throw new Error('This progress file has no saved daily entries.');const result={days:Object.create(null)};for(const [date,entry] of Object.entries(value.days)){if(!validDate(date)||!record(entry))continue;const day=byDate.get(date);const copy=Object.create(null);if(typeof entry.note==='string')copy.note=entry.note.slice(0,12000);else if(typeof entry.evidence==='string')copy.note=entry.evidence.slice(0,12000);for(const key of ['core','anki','explanation','practice','breaks','extra']){const task=key==='extra'?day?.optional_extra:day?.core;if(!task||typeof entry[key]!=='boolean')continue;const current=signature(task);const legacy=key==='core'||key==='extra'?task.task:task.task+':'+key;if(entry[key+'Signature']===current||(!entry[key+'Signature']&&entry[key+'Task']===legacy)){copy[key]=entry[key];copy[key+'Signature']=current;}}result.days[date]=copy;}return result;}
  function saveProgress(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify({viewer_format:FORMAT,plan_version:plan?.updated_on,reported_progress_only:true,official_completion_inferred:false,...state}));n['save-status'].textContent='Your study report is saved in this browser.';}catch(_){n['save-status'].textContent='Browser storage is unavailable or full. Use Save progress file to keep your report.';}}
  function savePlan(){try{localStorage.setItem(PLAN_KEY,JSON.stringify(plan));return true;}catch(_){return false;}}
  function monthList(){const set=new Set();for(const d of byDate.keys())set.add(d.slice(0,7));for(const req of array(plan.dated_requirements)){const range=requireRange(req);if(range)for(const d of range)set.add(d.slice(0,7));}for(const m of array(plan.planning_markers))for(const d of [m.start_date,m.end_date_exclusive])if(validDate(d))set.add(d.slice(0,7));for(const event of allEvents()){const range=eventRange(event);if(range)for(const d of range)set.add(d.slice(0,7));}if(!set.size)set.add(today().slice(0,7));const first=[...set].sort()[0],last=[...set].sort().at(-1);let d=first+'-01',guard=0;while(d.slice(0,7)<=last&&guard++<240){set.add(d.slice(0,7));const next=dateObj(d);next.setUTCMonth(next.getUTCMonth()+1);d=next.toISOString().slice(0,10);}return [...set].sort();}
  function setupPlan(value){plan=validatePlan(value);byDate=new Map(plan.days.map(d=>[d.date,d]));for(const week of plan.weeks)for(const d of week.days)if(byDate.has(d.date))byDate.set(d.date,{...byDate.get(d.date),...d,week_start:week.week_start});months=monthList();n.month.replaceChildren();for(const month of months){const option=el('option',monthFmt.format(dateObj(month+'-01')));option.value=month;n.month.append(option);}selected=today();if(!months.includes(selected.slice(0,7)))selected=months[0]+'-01';n.month.value=selected.slice(0,7);n.workspace.hidden=false;n.onboarding.hidden=true;n['progress-file'].disabled=false;n['export-progress'].disabled=false;n['work-note'].disabled=false;renderMetadata();renderMonth();renderDay();}
  function renderMetadata(){n.verification.replaceChildren();const list=el('dl');for(const [label,key] of [['Plan updated','updated_on'],['Course sources last verified','last_verified_course_sources'],['Calendar last verified','last_verified_calendar'],['Time zones recorded in plan','timezone']]){list.append(el('dt',label),el('dd',plan[key]||'Not recorded'));}list.append(el('dt','Weekly budget, including breaks'),el('dd',minutes(plan.weekly_base_minutes_including_breaks)+' base minutes / '+minutes(plan.weekly_possible_minutes_including_breaks)+' possible minutes. Individual and partial weeks are shown separately.'));n.verification.append(list,el('p','Loading this file does not refresh university sources or the calendar.','small muted'));if(plan.calendar_sync?.status)n.verification.append(el('p',plan.calendar_sync.status,'notice'));n['plan-notes'].replaceChildren();for(const key of ['assumption','completion_rule','replacement_rule','capacity_warning','availability_statement','user_report'])if(plan[key])n['plan-notes'].append(el('p',plan[key]));for(const value of array(plan.interpretation_notes))if(typeof value==='string')n['plan-notes'].append(el('p',value));if(record(plan.study_methods)){for(const key of ['anki','videos'])if(plan.study_methods[key])n['plan-notes'].append(el('p',plan.study_methods[key]));}}
  function renderMonth(){if(!plan)return;const month=n.month.value;n['month-title'].textContent=monthFmt.format(dateObj(month+'-01'));n['calendar-days'].replaceChildren();const first=dateObj(month+'-01'),offset=(first.getUTCDay()+6)%7,last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();for(let i=0;i<offset;i++){const blank=el('div');blank.setAttribute('aria-hidden','true');n['calendar-days'].append(blank);}for(let i=1;i<=last;i++){const date=month+'-'+String(i).padStart(2,'0'),d=byDate.get(date),req=requirements(date),mark=markers(date),events=commitments(date),button=el('button',undefined,'day'+(date===today()?' today':'')+(d&&reportedMinutes(d)>0?' done':''));button.type='button';button.setAttribute('aria-pressed',String(date===selected));button.setAttribute('aria-label',dateFmt.format(dateObj(date))+(d?.core?', '+text(d.core.course)+' '+minutes(d.core.total_minutes)+' minute study suggestion':'')+(d?.optional_extra?', optional study':'')+(req.length?', '+req.length+' recorded requirements':'')+(events.length?', '+events.length+' calendar commitments':''));button.append(el('span',i,'day-number'));if(d?.core)button.append(el('span',d.core.course,'day-tag'));else if(d?.optional_extra)button.append(el('span','Optional','day-tag'));if(req.length)button.append(el('span',req.length+' req.','day-tag'));if(mark.length)button.append(el('span',mark.length+' marker'+(mark.length>1?'s':''),'day-tag'));if(events.length)button.append(el('span',events.length+' event'+(events.length>1?'s':''),'day-tag'));button.addEventListener('click',()=>{flushNote();selected=date;renderMonth();renderDay();});n['calendar-days'].append(button);}const index=months.indexOf(month);n['previous-month'].disabled=index<=0;n['next-month'].disabled=index===months.length-1;}
  function toggleRow(label,key,task){const row=el('label',undefined,'check-row'),input=el('input');input.type='checkbox';input.checked=validTick(selected,key,task);input.addEventListener('change',()=>{const s=state.days[selected]||(state.days[selected]=Object.create(null));s[key]=input.checked;s[key+'Signature']=signature(task);saveProgress();renderWeek();renderMonth();});row.append(input,el('span',label));n.checklist.append(row);}
  function renderWeek(){const week=plan.weeks.find(w=>w.week_start<=selected&&w.week_end>=selected);if(!week){n['week-total'].textContent='No weekly study quota is recorded for this date.';return;}const reported=array(week.days).reduce((sum,d)=>sum+reportedMinutes(byDate.get(d.date)||d),0),base=minutes(week.base_minutes_including_breaks),extra=minutes(week.optional_extra_minutes_including_breaks),max=week.maximum_minutes_including_breaks==null?base+extra:minutes(week.maximum_minutes_including_breaks),scheduled=array(week.days).reduce((sum,d)=>sum+minutes(d.core?.total_minutes),0);n['week-total'].textContent='Week '+week.week_start+': '+base+' base minutes + '+extra+' optional, including breaks. '+reported+' minutes reported complete.'+(scheduled!==base?' The dated core blocks total '+scheduled+' minutes; review the difference.':'')+(reported>max?' Your report exceeds the '+max+'-minute maximum; review your capacity.':'');if(week.planning_note)n['week-total'].textContent+=' '+week.planning_note;}
  function renderDay(){if(!plan)return;const d=byDate.get(selected);n['day-title'].textContent=dateFmt.format(dateObj(selected));n.checklist.replaceChildren();n['work-note'].value=state.days[selected]?.note||'';n['work-note'].disabled=false;renderWeek();if(d?.historical_plan_only)n.checklist.append(el('p','Historical planning record: no completed study is inferred.','notice'));if(d?.core){const c=d.core;n.checklist.append(el('h3',text(c.course)+' · '+minutes(c.total_minutes)+' minutes including breaks'),el('p',c.task));if(c.components){for(const [key,field,label] of COMPONENTS)toggleRow(minutes(c.components[field])+' minutes · '+label,key,c);const links=el('div',undefined,'links');helperLink(links,'Open this course’s practice cards','anki',c.learning_course_code);helperLink(links,'Choose a matched explanation','video',c.learning_course_code);sourceLink(links,'Task source ↗',c.source_url);n.checklist.append(links);}else{const links=el('div',undefined,'links');sourceLink(links,'Task source ↗',c.source_url);n.checklist.append(links);}toggleRow('Whole core session completed, including its breaks','core',c);n.checklist.append(el('p','The whole-session tick overrides its component ticks when minutes are counted.','small muted'));}else n.checklist.append(el('p',d?.task||'No core study block is recorded for this date.'));if(d?.optional_extra){const c=d.optional_extra;n.checklist.append(el('h3','Optional · '+minutes(c.total_minutes)+' minutes including breaks'),el('p',c.task));toggleRow('Optional block completed, including its breaks','extra',c);if(d.replacement_only_note)n.checklist.append(el('p',d.replacement_only_note,'small muted'));}if(d?.suggested_day_only)n.checklist.append(el('p','Suggested day only. Redistribute within the weekly budget; no free clock slot is assumed.','small muted'));renderRequirements();renderUpcoming();}
  function requirementCard(item){const range=requireRange(item),card=el('article',undefined,'requirement'+(/tentative|provisional|unknown|unconfirmed|uncertain|conflict|if |conditional/i.test(text(item.certainty)+' '+text(item.note))?' uncertain':''));card.append(el('h3',text(item.course)+(item.course?' — ':'')+text(item.item)),el('p',range?(range[0]===range[1]?range[0]:range.join(' to ')):'No confirmed date','date-only'));card.append(el('p',(item.official_time||'Exact time not recorded.')+(item.timezone?' · '+item.timezone:'')));if(item.certainty)card.append(el('p',item.certainty));if(item.note)card.append(el('p',item.note));const details=el('dl');for(const [label,key] of [['Official date','official_date'],['Official window end','official_window_end'],['Personal finish target (not official)','personal_deadline'],['Personal follow-up target (not official)','personal_followup_target'],['Recorded completion status','completion_status'],['Submission destination','submission_destination'],['File format','file_format'],['Naming requirements','naming_requirements'],['Citation style','citation_style'],['Successful submission evidence required','successful_submission_evidence']])if(item[key])details.append(el('dt',label),el('dd',item[key]));if(details.childNodes.length)card.append(details);card.append(el('p','Source last checked: '+(item.source_checked_on||'Not recorded')+'. This viewer has not rechecked it.','metadata'));const links=el('div',undefined,'links');sourceLink(links,'University/source record ↗',item.source_url);for(const value of array(item.related_request_source_urls))sourceLink(links,'Related request source ↗',value);if(links.childNodes.length)card.append(links);return card;}
  function renderRequirements(){n.requirements.replaceChildren();let count=0;for(const update of array(plan.review_updates))if(validDate(update.date)&&validDate(update.through)&&update.date<=selected&&update.through>=selected){const card=el('article',undefined,'notice');card.append(el('h3',update.title),el('p',update.text));sourceLink(card,'Recorded source ↗',update.source_url);n.requirements.append(card);count++;}for(const item of requirements(selected)){n.requirements.append(requirementCard(item));count++;}for(const marker of markers(selected)){const card=el('article',undefined,'requirement uncertain');card.append(el('h3',marker.title),el('p',marker.kind||'Planning marker'),el('p',marker.description||'A planning/calendar marker, not evidence of completed or submitted work.'));sourceLink(card,'Saved calendar reminder ↗',marker.url);n.requirements.append(card);count++;}for(const event of commitments(selected)){const card=el('article',undefined,'commitment');card.append(el('h3',event.title));const range=eventRange(event);if(eventKind(event)==='date')card.append(el('p','Date reminder: '+range[0]+(range[1]!==range[0]?' to '+range[1]:'')));else if(eventKind(event)==='floating')card.append(el('p',text(event.start).slice(11,16)+'–'+text(event.end).slice(11,16)+' · floating clock time; timezone not recorded. Confirm the source time.'));else{const start=new Date(event.start),end=new Date(event.end);card.append(el('p',campusTimeFmt.format(start)+(Number.isNaN(end.getTime())?'':'–'+campusTimeFmt.format(end))+' · Europe/Lisbon (campus time)'));}if(event.location)card.append(el('p',event.location));if(event.response)card.append(el('p','Calendar response: '+event.response+'. This does not confirm attendance or section approval.'));if(event.transparency==='transparent')card.append(el('p','Shown as free in Calendar; this may be a reminder or placeholder.'));card.append(el('p','Calendar record checked: '+(event.calendar_checked_on||plan.last_verified_calendar||'Not recorded'),'metadata'));sourceLink(card,'Open saved calendar event ↗',event.url);n.requirements.append(card);count++;}const calendar=plan.official_calendar||{};if(array(calendar.holidays).includes(selected)){n.requirements.append(el('p','Recorded university holiday. Check teaching arrangements; a holiday does not cancel a posted deadline.','notice'));count++;}if(array(calendar.christmas_vacation).length===2&&calendar.christmas_vacation[0]<=selected&&calendar.christmas_vacation[1]>=selected){n.requirements.append(el('p','Recorded university vacation period. Study remains flexible; posted deadlines still apply.','notice'));count++;}if(!count)n.requirements.append(el('p','No dated requirement or calendar commitment appears in the loaded records for this day. This does not establish free time.','muted'));}
  function renderUpcoming(){const end=addDays(selected,30),items=array(plan.dated_requirements).filter(item=>{const r=requireRange(item);return r&&r[1]>=selected&&r[0]<=end;}).sort((a,b)=>requireRange(a)[0].localeCompare(requireRange(b)[0]));n.upcoming.replaceChildren();for(const item of items)n.upcoming.append(requirementCard(item));if(!items.length)n.upcoming.append(el('p','No dated requirements in this 30-day window in the loaded file. New Moodle requirements may still exist.','muted'));n.undated.replaceChildren();const missing=[...array(plan.undated_requirements),...array(plan.dated_requirements).filter(item=>!requireRange(item))];for(const item of missing)n.undated.append(requirementCard(item));if(!missing.length)n.undated.append(el('p','No undated requirement is recorded in this file.','muted'));}
  function flushNote(){if(noteTimer){clearTimeout(noteTimer);noteTimer=undefined;}if(!plan||!validDate(selected))return;const s=state.days[selected]||(state.days[selected]=Object.create(null));s.note=n['work-note'].value.slice(0,12000);saveProgress();}
  async function parseFile(input){const file=input.files?.[0];if(!file)return null;if(file.size>MAX_FILE)throw new Error('Choose a JSON file smaller than 10 MB.');return JSON.parse(await file.text());}
  n['plan-file'].addEventListener('change',async()=>{try{flushNote();const value=await parseFile(n['plan-file']);if(value===null)return;validatePlan(value);setupPlan(value);state=safeProgress(state);renderMonth();renderDay();saveProgress();const persisted=savePlan();status('Private plan loaded. Imported plan flags do not mark work complete.'+(persisted?' It is retained in this browser.':' Browser storage is unavailable or full; reload the plan file next time.'),!persisted);}catch(error){status('Plan not loaded: '+text(error.message),true);}finally{n['plan-file'].value='';}});
  n['progress-file'].addEventListener('change',async()=>{if(!plan)return;try{flushNote();const value=await parseFile(n['progress-file']);if(value===null)return;const imported=safeProgress(value);for(const [date,entry] of Object.entries(imported.days))state.days[date]={...(state.days[date]||{}),...entry};saveProgress();renderMonth();renderDay();status('Matching study reports imported. Changed task checks are ignored; no official completion is inferred.');}catch(error){status('Progress not imported: '+text(error.message),true);}finally{n['progress-file'].value='';}});
  n['export-progress'].addEventListener('click',()=>{if(!plan)return;flushNote();const data={viewer_format:FORMAT,plan_version:plan.updated_on,exported_at:new Date().toISOString(),reported_progress_only:true,official_completion_inferred:false,...state},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='academic-study-progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);n['save-status'].textContent='Progress file download requested. Keep it as a private backup.';});
  n['work-note'].addEventListener('input',()=>{clearTimeout(noteTimer);noteTimer=setTimeout(flushNote,300);});
  n.month.addEventListener('change',()=>{flushNote();selected=n.month.value+'-01';renderMonth();renderDay();});
  for(const [id,step] of [['previous-month',-1],['next-month',1]])n[id].addEventListener('click',()=>{const index=months.indexOf(n.month.value)+step;if(index<0||index>=months.length)return;flushNote();n.month.value=months[index];selected=months[index]+'-01';renderMonth();renderDay();});
  n.today.addEventListener('click',()=>{if(!plan)return;flushNote();selected=today();const month=selected.slice(0,7);if(!months.includes(month)){months.push(month);months.sort();n.month.replaceChildren();for(const m of months){const option=el('option',monthFmt.format(dateObj(m+'-01')));option.value=m;n.month.append(option);}}n.month.value=month;renderMonth();renderDay();});
  window.addEventListener('pagehide',flushNote);
  try{const stored=localStorage.getItem(PLAN_KEY);if(stored){setupPlan(JSON.parse(stored));const progress=localStorage.getItem(PROGRESS_KEY);if(progress)state=safeProgress(JSON.parse(progress));renderMonth();renderDay();status('Saved private plan restored from this browser. It is not automatically refreshed.');}}catch(_){status('Saved data could not be restored. Choose your plan file; use a saved progress file if available.',true);}
})();
