'use strict';
(() => {
  const FORMAT='evora-phone-progress-v1', STORE='evora-today-progress-v1', COORDS='evora-today-private-repo-v1';
  const API='https://api.github.com', OWNER='Hostilian', DATA_REPO='EVORA-STUDY-PROGRESS', MAX_FILE=2*1024*1024;
  const plain=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
  const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
  const addDays=(v,n)=>{const d=new Date(v+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
  const weekStart=v=>addDays(v,-((new Date(v+'T12:00:00Z').getUTCDay()+6)%7));
  const validTime=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&Date.parse(v)<=Date.now()+5*60*1000;
  const num=v=>Number.isFinite(v)&&v>=0?v:0;
  const safeURL=v=>{try{const u=new URL(v,typeof location==='object'?location.href:'https://hostilian.github.io/EVORACLASSES/study/today.html');return u.protocol==='https:'&&!u.username&&!u.password&&!['localhost','127.0.0.1','[::1]'].includes(u.hostname)?u.href:null;}catch(_){return null;}};
  function validatePlan(p){
    if(!plain(p)||p.format!=='evora-public-suggested-plan-v1'||!validDate(p.updated_on)||!validDate(p.study_start)||!validDate(p.study_end)||p.study_end<p.study_start||!Array.isArray(p.requirements)||!Array.isArray(p.courses)||p.weekly_base_minutes!==420||p.weekly_max_minutes!==480)throw Error('General plan format is invalid.');
    for(const r of p.requirements)if(!validDate(r.date)||!validDate(r.end_date)||r.end_date<r.date||!safeURL(r.source_url))throw Error('A course date or source is invalid.');
    const overrides=p.dated_priority_overrides===undefined?[]:p.dated_priority_overrides;
    if(!Array.isArray(overrides)||overrides.length>3000)throw Error('Dated priorities are invalid.');
    const dates=new Set();
    for(const o of overrides){
      if(!plain(o)||!validDate(o.date)||dates.has(o.date)||!coreLimit(o.date,p)||!validDate(o.reviewed_on)||o.reviewed_on>p.updated_on||!validDate(o.source_checked_on)||o.source_checked_on>o.reviewed_on||o.official_deadlines_shifted!==false||!Array.isArray(o.source_urls)||!o.source_urls.length||o.source_urls.length>20||o.source_urls.some(url=>!safeURL(url))||!Array.isArray(o.priorities)||o.priorities.length<1||o.priorities.length>3||o.break_minutes!==10)throw Error('A dated priority has invalid dates, sources or capacity.');
      dates.add(o.date);
      const taskIds=new Set();let minutes=o.break_minutes;
      for(const t of o.priorities){
        if(!plain(t)||typeof t.id!=='string'||!/^[a-zA-Z0-9-]{1,70}$/.test(t.id)||['break-1','break-2'].includes(t.id)||taskIds.has(t.id)||typeof t.title!=='string'||!t.title.trim()||t.title.length>250||!Number.isInteger(t.minutes)||t.minutes<=0||typeof t.text!=='string'||t.text.length>3000||t.signature!==undefined||t.done!==undefined||t.checked!==undefined||t.kind!==undefined||t.course!==undefined&&typeof t.course!=='string'||t.start!==undefined&&(typeof t.start!=='string'||t.start.length>600)||t.consequence!==undefined&&(typeof t.consequence!=='string'||t.consequence.length>600)||t.links!==undefined&&(!Array.isArray(t.links)||t.links.length>8||t.links.some(l=>!plain(l)||typeof l.label!=='string'||!safeURL(l.url))))throw Error('A dated priority task is invalid.');
        taskIds.add(t.id);minutes+=t.minutes;
      }
      if(minutes!==coreLimit(o.date,p))throw Error('Dated priorities must replace the day within its existing allowance.');
    }
    return p;
  }
  function taskSignature(t){return t.signature||JSON.stringify([t.id,t.title,t.minutes,t.course||'',t.text||'',t.kind]);}
  function withSignature(t){return {...t,signature:taskSignature(t)};}
  const compactText=(value,limit=600)=>String(value||'').trim().replace(/\s+/gu,' ').slice(0,limit);
  function coreLimit(date,p){if(date<p.study_start||date>p.study_end)return 0;return new Date(date+'T12:00:00Z').getUTCDay()===0?0:date<='2026-10-10'?105:70;}
  function dayLimit(date,p){if(date<p.study_start||date>p.study_end)return 0;const wd=new Date(date+'T12:00:00Z').getUTCDay();return wd===0?60:date<='2026-10-10'?105:70;}
  function weekBudget(date,p){const start=weekStart(date);let base=0,optional=0;for(let i=0;i<7;i++){const d=addDays(start,i),limit=dayLimit(d,p);if(new Date(d+'T12:00:00Z').getUTCDay()===0)optional+=limit;else base+=limit;}return {start,base,max:Math.min(p.weekly_max_minutes,base+optional)};}
  function dailyTasks(date,p,privatePlans={}){
    if(privatePlans[date])return privatePlans[date].tasks.map(t=>({...t}));
    if(!coreLimit(date,p))return [];
    const override=(p.dated_priority_overrides||[]).find(o=>o.date===date);
    if(override)return override.priorities.map(t=>withSignature({...t,kind:'priority'})).concat([1,2].map(i=>withSignature({id:'break-'+i,title:'Take a five-minute break',minutes:5,kind:'break'})));
    if(date===p.study_start)return p.initial_priorities.map(t=>withSignature({...t,kind:'priority'})).concat([1,2].map(i=>withSignature({id:'break-'+i,title:'Take a five-minute break',minutes:5,kind:'break'})));
    const wd=new Date(date+'T12:00:00Z').getUTCDay(),name=date==='2026-10-08'?'Web':date==='2026-10-09'?'Statistics':date==='2026-10-10'?'Software':['Data','Data','HCI','Web','Statistics','Software','Data'][wd];
    const c=p.courses.find(c=>c.name===name),code=c?.code,capacity=coreLimit(date,p),study='https://hostilian.github.io/EVORACLASSES/study/';
    const tasks=[{id:'anki',title:name+': review due Anki cards',minutes:10,kind:'priority',course:name,text:'Use native Anki due cards first. Browser card practice does not change native due scheduling.',start:'Try five due cards before revealing their backs.',links:[{label:'Course cards',url:study+'anki_cards.html?course='+code+'&track=foundation'}]},
      {id:'explanation',title:name+': one matched explanation',minutes:15,kind:'priority',course:name,text:'Watch one relevant segment or read the matching notes, then explain one idea from memory.',links:[{label:'Course helper and videos',url:study+'courses/'+code+'.html#video-explanations'}]},
      {id:'practice',title:name+': independent practice or the next required step',minutes:capacity-35,kind:'priority',course:name,text:'Attempt one small exercise or real project step yourself. Check the course AI rules before assessed work.',start:'Write one question you will answer in this block.',consequence:'Keep the attempt and its errors; watching alone does not establish mastery.'}];
    const urgent=p.requirements.filter(r=>date<=r.date&&r.date<=addDays(date,3)).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
    if(urgent.length){const r=urgent[0];tasks[2]={id:'practice',title:compactText('Check '+r.course+': '+r.title,200),minutes:capacity-35,kind:'priority',course:r.course,text:compactText('Condition: '+(r.condition||'None stated')+'. '+(r.note||'')),consequence:'Posted date '+r.date+'; '+(r.certainty||'certainty unspecified'),links:[{label:'Official source',url:r.source_url}]};}
    tasks.push(...[1,2].map(i=>({id:'break-'+i,title:'Take a five-minute break',minutes:5,kind:'break'})));
    return tasks.map(withSignature);
  }
  function initialOptional(p){let remaining=25;return p.optional_actions.filter(t=>{if(t.minutes<=remaining){remaining-=t.minutes;return true;}return false;});}
  function optionalTasks(date,p,privatePlans={}){
    if(privatePlans[date])return privatePlans[date].optional_tasks.map(t=>({...t}));
    if(date<p.study_start||date>p.study_end)return [];
    const budget=weekBudget(date,p),inWeek=d=>budget.start<=d&&d<addDays(budget.start,7);
    let reserved=Object.entries(privatePlans).filter(([d])=>d!==date&&inWeek(d)).reduce((s,[,v])=>s+v.optional_minutes,0);
    if(date!==p.study_start&&inWeek(p.study_start)&&!privatePlans[p.study_start])reserved+=initialOptional(p).reduce((s,t)=>s+t.minutes,0);
    let remaining=Math.max(0,budget.max-budget.base-reserved),items=[];
    if(date===p.study_start){remaining=Math.min(25,remaining);for(const t of p.optional_actions)if(t.minutes<=remaining){items.push(t);remaining-=t.minutes;}}
    else if(new Date(date+'T12:00:00Z').getUTCDay()===0&&remaining>=20)items=[{id:'optional-anki',title:'Optional due Anki review',minutes:10},{id:'optional-practice',title:'Optional priority practice or catch-up',minutes:Math.min(60,remaining)-15,text:'Use one genuine attempt or unfinished prerequisite. This is the optional eighth-hour allocation, including its break.'},{id:'optional-break',title:'Take a five-minute break',minutes:5}];
    return items.map(t=>withSignature({...t,kind:'optional'}));
  }
  function packet(date,p,entry={tasks:{}},privatePlans={}){
    const available=new Map([...dailyTasks(date,p,privatePlans),...optionalTasks(date,p,privatePlans)].map(t=>[t.id,t]));
    const tasks=[],archived=[...(entry.archived_tasks||[])];for(const [id,r] of Object.entries(entry.tasks||{})){if((!available.has(id)||r.signature!==taskSignature(available.get(id)))&&typeof r.done==='boolean'&&validTime(r.user_reported_at))archived.push({id,done:r.done,signature:r.signature,user_reported_at:r.user_reported_at,title:r.title||'Earlier task report',minutes:num(r.minutes),kind:r.kind||'priority'});const t=available.get(id);if(t&&typeof r.done==='boolean'&&r.signature===taskSignature(t)&&validTime(r.user_reported_at))tasks.push({id,title:t.title,kind:t.kind,done:r.done,minutes:t.minutes,signature:r.signature,user_reported_at:r.user_reported_at});}
    const review=entry.day_review&&typeof entry.day_review.note==='string'&&validTime(entry.day_review.user_reported_at)?{note:entry.day_review.note.slice(0,3000),user_reported_at:entry.day_review.user_reported_at}:undefined;
    const times=tasks.map(t=>t.user_reported_at).concat(review?[review.user_reported_at]:[]).sort();
    const out={schema_version:1,format:FORMAT,date,timezone:'Europe/London',plan_revision:privatePlans[date]?.plan_revision||p.updated_on,updated_at:times.at(-1)||new Date().toISOString(),reported_status:tasks.length||review?'reported':'unreported',reported_minutes:tasks.filter(t=>t.done).reduce((s,t)=>s+t.minutes,0),tasks,official_completion_inferred:false};if(review)out.day_review=review;if(archived.length)out.archived_tasks=[...new Map(archived.map(t=>[[t.id,t.signature,t.user_reported_at,t.done].join('|'),t])).values()].slice(-200);return out;
  }
  function parsePacket(raw,date){if(!plain(raw)||raw.schema_version!==1||raw.format!==FORMAT||raw.date!==date||!validDate(date)||!Array.isArray(raw.tasks)||raw.tasks.length>30)throw Error('Saved progress format is invalid.');const out={tasks:Object.create(null)};for(const t of raw.tasks){if(!plain(t)||typeof t.id!=='string'||!/^[a-zA-Z0-9-]{1,70}$/.test(t.id)||typeof t.done!=='boolean'||typeof t.signature!=='string'||t.signature.length>6000||!validTime(t.user_reported_at))throw Error('A report has an invalid task or timestamp. Check the device clock.');if(out.tasks[t.id])throw Error('A report contains a duplicated task.');out.tasks[t.id]={done:t.done,signature:t.signature,user_reported_at:t.user_reported_at,title:typeof t.title==='string'?t.title.slice(0,250):'Earlier task report',minutes:num(t.minutes),kind:['priority','break','optional'].includes(t.kind)?t.kind:'priority'};}if(Array.isArray(raw.archived_tasks))out.archived_tasks=raw.archived_tasks.slice(-200).filter(t=>plain(t)&&typeof t.id==='string'&&typeof t.done==='boolean'&&typeof t.signature==='string'&&t.signature.length<=6000&&validTime(t.user_reported_at)).map(t=>({id:t.id.slice(0,70),done:t.done,signature:t.signature,user_reported_at:t.user_reported_at,title:typeof t.title==='string'?t.title.slice(0,250):'Earlier task report',minutes:num(t.minutes),kind:['priority','break','optional'].includes(t.kind)?t.kind:'priority'}));if(raw.day_review){if(typeof raw.day_review.note!=='string'||!validTime(raw.day_review.user_reported_at))throw Error('Saved note format is invalid.');out.day_review={note:raw.day_review.note.slice(0,3000),user_reported_at:raw.day_review.user_reported_at};}return out;}
  function mergeEntries(local={},remote={}){
    const out={tasks:Object.create(null),archived_tasks:[...new Map([...(local.archived_tasks||[]),...(remote.archived_tasks||[])].map(t=>[[t.id,t.signature,t.user_reported_at,t.done].join('|'),t])).values()].slice(-200)},conflicts=[];
    for(const id of new Set([...Object.keys(local.tasks||{}),...Object.keys(remote.tasks||{})])){const a=local.tasks?.[id],b=remote.tasks?.[id];if(!a||!b){out.tasks[id]={...(a||b)};continue;}if(a.signature!==b.signature)out.archived_tasks.push({id,...(a.user_reported_at>b.user_reported_at?b:a)});if(a.user_reported_at===b.user_reported_at&&(a.done!==b.done||a.signature!==b.signature)){conflicts.push(id);out.tasks[id]={...a};}else out.tasks[id]={...(a.user_reported_at>b.user_reported_at?a:b)};}
    const a=local.day_review,b=remote.day_review;if(a&&b&&a.user_reported_at===b.user_reported_at&&a.note!==b.note){conflicts.push('day_review');out.day_review={...a};}else if(a||b)out.day_review={...(!b||a&&a.user_reported_at>b.user_reported_at?a:b)};
    return {entry:out,conflicts};
  }
  function validatePrivateDay(raw,date,p){
    if(!plain(raw)||raw.schema_version!==1||raw.format!=='evora-daily-proposal-v1'||raw.date!==date||raw.timezone!=='Europe/London'||raw.status!=='suggested'||raw.task_completion_prechecked!==false||raw.official_completion_inferred!==false||!Array.isArray(raw.tasks)||raw.tasks.length>5||raw.tasks.some(t=>!plain(t)||!['priority','break'].includes(t.kind))||raw.tasks.filter(t=>t.kind==='priority').length>3||raw.tasks.filter(t=>t.kind==='break').length>2)throw Error('Private day suggestion is invalid.');
    const task=t=>{if(!plain(t)||typeof t.id!=='string'||!/^[a-zA-Z0-9-]{1,70}$/.test(t.id)||typeof t.title!=='string'||t.title.length>250||!Number.isInteger(t.minutes)||t.minutes<=0||t.minutes>105||!['priority','break','optional'].includes(t.kind)||typeof t.signature!=='string'||t.signature.length>6000)throw Error('Private task format is invalid.');return {...t,text:typeof t.text==='string'?t.text.slice(0,3000):'',start:typeof t.start==='string'?t.start.slice(0,600):'',consequence:typeof t.consequence==='string'?t.consequence.slice(0,600):'',links:Array.isArray(t.links)?t.links.slice(0,8).filter(l=>plain(l)&&typeof l.label==='string'&&safeURL(l.url)):[]};};
    const tasks=raw.tasks.map(task),sum=tasks.reduce((s,t)=>s+t.minutes,0);
    if(sum!==coreLimit(date,p)||raw.core_minutes!==sum||new Set(tasks.map(t=>t.id)).size!==tasks.length)throw Error('Private suggestion exceeds the selected-day budget or contains duplicated tasks.');
    if(!Array.isArray(raw.optional_tasks)||raw.optional_tasks.length>3)throw Error('Optional private task format is invalid.');
    const optional=raw.optional_tasks.map(task),optionalSum=optional.reduce((s,t)=>s+t.minutes,0),allowance=date===p.study_start?25:new Date(date+'T12:00:00Z').getUTCDay()===0?60:0;
    if(optional.some(t=>t.kind!=='optional')||new Set(tasks.concat(optional).map(t=>t.id)).size!==tasks.length+optional.length||optionalSum>allowance||raw.optional_minutes!==optionalSum)throw Error('Optional private task format is invalid.');
    return {...raw,tasks,optional_tasks:optional};
  }
  function reportedMinutes(date,p,state,privatePlans={}){return packet(date,p,state.days?.[date],privatePlans).reported_minutes;}
  function nextProposal(date,p,state,privatePlans={}){
    const next=addDays(date,1),budget=weekBudget(next,p),start=budget.start;
    let already=0;for(let i=0;i<7;i++)already+=reportedMinutes(addDays(start,i),p,state,privatePlans);
    const offered=dailyTasks(next,p,privatePlans),optional=optionalTasks(next,p,privatePlans),offeredMinutes=offered.concat(optional).reduce((s,t)=>s+t.minutes,0);
    const capacity=Math.max(0,Math.min(offeredMinutes,budget.max-already));
    if(capacity<15)return {date:next,minutes:0,tasks:[],reason:dayLimit(next,p)?'The reported week has reached its allowance. Rest or replace an existing lower-priority block; no extra hours are added.':'No core study block is suggested outside this plan’s study range.'};
    const current=dailyTasks(date,p,privatePlans),unfinished=current.find(t=>t.kind==='priority'&&!['anki','explanation'].includes(t.id)&&state.days?.[date]?.tasks?.[t.id]?.signature===taskSignature(t)&&state.days[date].tasks[t.id].done===false);
    const nextTasks=offered.map(t=>({...t}));let carried=false;
    const practice=nextTasks.find(t=>t.id==='practice'&&t.kind==='priority');
    if(unfinished&&practice){practice.title='Continue: '+compactText(unfinished.title,180);carried=true;}
    const choices=coreLimit(next,p)?nextTasks:optional,tasks=[];let remaining=capacity;
    for(const t of choices){if(remaining<=0)break;const minutes=Math.min(t.minutes,remaining);tasks.push({title:t.title,minutes});remaining-=minutes;}
    return {date:next,minutes:tasks.reduce((sum,t)=>sum+t.minutes,0),tasks,reason:carried?'One explicitly reported unfinished focus replaces the next practice allocation; no extra hours are added.':'Use the next planned topic. Untouched checkboxes remain unreported; no unfinished task is inferred.'};
  }
  if(typeof module==='object'&&module.exports){module.exports={validatePlan,taskSignature,dailyTasks,optionalTasks,weekBudget,dayLimit,coreLimit,packet,parsePacket,mergeEntries,validatePrivateDay,nextProposal,validDate,validTime};return;}
  const ids=['load-status','app','selected-title','date','previous-day','next-day','today','capacity','priorities','breaks','note','save-status','proposal','optional','course-links','month','month-summary','upcoming','undated','export','import','backup-status','repo-owner','repo-name','repo-token','connect','disconnect','sync-now','sync-status','resolve-conflicts'];
  const n=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  const df=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}),lf=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/London'});
  const queryDate=new URLSearchParams(location.search||'').get('date');let plan,state={days:Object.create(null)},selected=validDate(queryDate)?queryDate:lf.format(new Date()),privatePlans=Object.create(null),noteTimer,syncTimer,syncing=false,token='',cloud=null,conflicts=[],pending=new Map();
  const element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;};
  function message(id,text,error=false){n[id].textContent=text;n[id].className=(id==='sync-status'?'notice':'small')+(error?' error':'');}
  function stamp(){let latest=Date.now();for(const d of Object.values(state.days))for(const t of [...Object.values(d.tasks||{}),...(d.day_review?[d.day_review]:[])])if(validTime(t.user_reported_at))latest=Math.max(latest,Date.parse(t.user_reported_at)+1);return new Date(latest).toISOString();}
  function entry(date=selected){return state.days[date]||(state.days[date]={tasks:Object.create(null)});}
  function save(){try{localStorage.setItem(STORE,JSON.stringify({format:FORMAT,days:Object.fromEntries(Object.entries(state.days).map(([d,e])=>[d,packet(d,plan,e,privatePlans)]))}));message('save-status','Saved in this browser.');}catch(_){message('save-status','Browser storage is unavailable or full. Save a private progress file.',true);}}
  function queueSync(){if(!cloud)return;clearTimeout(syncTimer);message('sync-status','Private sync pending; your report is already saved in this browser.');const date=selected;syncTimer=setTimeout(()=>syncDate(date,true),1200);}
  function links(parent,items){const wrap=element('div',undefined,'links');for(const l of items||[]){const url=safeURL(l.url);if(!url)continue;const a=element('a',l.label);a.href=url;if(new URL(url).origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}wrap.append(a);}if(wrap.childNodes.length)parent.append(wrap);}
  function checkbox(t,simple=false){
    const row=element(simple?'label':'article',undefined,simple?'simple-task':'priority'),label=simple?row:element('label',undefined,'task-label'),input=element('input');input.type='checkbox';
    const saved=state.days[selected]?.tasks?.[t.id],matches=saved&&saved.signature===taskSignature(t);input.checked=!!(matches&&saved.done===true);
    const reportNote=element('span',matches?(saved.done?'Reported done':'Reported not done yet'):'No progress reported','small muted');reportNote.setAttribute('aria-live','polite');
    const report=done=>{const e=entry(),old=e.tasks[t.id];if(old&&old.signature!==taskSignature(t))e.archived_tasks=[...(e.archived_tasks||[]),{id:t.id,...old}].slice(-200);e.tasks[t.id]={done,signature:taskSignature(t),user_reported_at:stamp(),title:t.title,minutes:t.minutes,kind:t.kind};input.checked=done;reportNote.textContent=done?'Reported done':'Reported not done yet';save();renderCapacity();renderProposal();queueSync();};
    input.addEventListener('change',()=>report(input.checked));label.append(input,element('span',t.title+(simple?'':' · '+t.minutes+' min')));
    if(simple){label.append(element('span',t.minutes+' min','time'));return row;}
    row.append(label);
    if(t.kind==='priority'){const unfinished=element('button','Not done yet');unfinished.type='button';unfinished.setAttribute('aria-label','Report '+t.title+' as not done yet');unfinished.addEventListener('click',()=>report(false));row.append(unfinished,reportNote);}
    const body=element('div',undefined,'task-copy');if(t.text)body.append(element('p',t.text));if(t.start)body.append(element('p','Five-minute start: '+t.start,'start'));if(t.consequence)body.append(element('p',t.consequence,'consequence'));links(body,t.links);row.append(body);return row;
  }
  function renderCapacity(){const b=weekBudget(selected,plan);let total=0;for(let i=0;i<7;i++)total+=reportedMinutes(addDays(b.start,i),plan,state,privatePlans);const core=coreLimit(selected,plan),optional=optionalTasks(selected,plan,privatePlans).reduce((s,t)=>s+t.minutes,0),daily=core+optional;n.capacity.textContent=(daily?(core?core+' core suggested minutes today':'No core block today')+(optional?' · up to '+optional+' optional minutes':''):'No core block is suggested for this date')+'. Week starting '+b.start+': '+b.base+' base / '+b.max+' maximum minutes including breaks. '+total+' suggested minutes attached to completed ticks.'+(total>b.max?' Review this report: it exceeds the weekly allowance.':'');}
  function renderProposal(){n.proposal.replaceChildren();const p=nextProposal(selected,plan,state,privatePlans);n.proposal.append(element('h3',df.format(new Date(p.date+'T12:00:00Z'))+' · '+p.minutes+' min'));for(const t of p.tasks)n.proposal.append(element('div',t.minutes+' min · '+t.title,'proposal-item'));n.proposal.append(element('p',p.reason,'small muted'));}
  function renderDay(){n.date.value=selected;n['selected-title'].textContent=df.format(new Date(selected+'T12:00:00Z'));n.priorities.replaceChildren();n.breaks.replaceChildren();for(const t of dailyTasks(selected,plan,privatePlans))(t.kind==='break'?n.breaks:n.priorities).append(checkbox(t,t.kind==='break'));if(!dayLimit(selected,plan))n.priorities.append(element('p','Review upcoming requirements. The saved study suggestions end on '+plan.study_end+'.'));if(privatePlans[selected])n.priorities.prepend(element('p','Private suggested plan loaded. Source limitations: '+(Array.isArray(privatePlans[selected].source_limitations)?privatePlans[selected].source_limitations.join(' '):privatePlans[selected].source_limitations||'Consult the original course sources.'),'notice'));n.note.value=state.days[selected]?.day_review?.note||'';n.optional.replaceChildren();for(const t of optionalTasks(selected,plan,privatePlans))n.optional.append(checkbox(t,true));renderCapacity();renderProposal();}
  function requirementCard(r){const uncertain=/provisional|inferred|planning|unconfirmed|pending/i.test(r.certainty||''),card=element('article',undefined,'requirement'+(uncertain?' uncertain':''));card.append(element('h3',r.course+' · '+r.title));if(r.date)card.append(element('p',r.date+(r.end_date!==r.date?' to '+r.end_date:''),'date-label'));if(r.condition)card.append(element('span',r.condition,'badge'));if(r.certainty)card.append(element('p',r.certainty));if(r.date)card.append(element('p',(r.time||'Exact time not published / confirmed')+(r.timezone?' · '+r.timezone:'. Timezone not separately stated in the saved source; confirm campus time.')));if(r.note)card.append(element('p',r.note));card.append(element('p','Source last checked '+r.source_checked_on+'. The page has not rechecked it.','metadata'));links(card,[{label:'Open Moodle source ↗',url:r.source_url}]);return card;}
  function renderMonth(){n.upcoming.replaceChildren();const month=n.month.value,list=plan.requirements.filter(r=>r.date.slice(0,7)<=month&&r.end_date.slice(0,7)>=month).sort((a,b)=>a.date.localeCompare(b.date));for(const r of list)n.upcoming.append(requirementCard(r));n['month-summary'].textContent=list.length+' recorded course requirement'+(list.length===1?'':'s')+' overlap this month. '+plan.source_limit;if(!list.length)n.upcoming.append(element('p','No dated requirements appear in the saved source facts for this month. Check Moodle for new or unposted work.'));n.undated.replaceChildren();for(const r of plan.undated_requirements)n.undated.append(requirementCard(r));}
  function renderCourseLinks(){for(const c of plan.courses){const card=element('div',undefined,'course-link');card.append(element('h3',c.name));links(card,[{label:'Helper & videos',url:'courses/'+c.code+'.html'},{label:'Cards',url:'anki_cards.html?course='+c.code+'&track=foundation'}]);n['course-links'].append(card);}}
  function flushNote(){clearTimeout(noteTimer);if(n.note.value!==(state.days[selected]?.day_review?.note||'')){entry().day_review={note:n.note.value.slice(0,3000),user_reported_at:stamp()};save();queueSync();}}
  function selectDate(date){if(!validDate(date))return;flushNote();selected=date;n.month.value=date.slice(0,7);renderDay();renderMonth();if(cloud)syncDate(date,false);}
  function apiPath(){return '/repos/'+encodeURIComponent(cloud.owner)+'/'+encodeURIComponent(cloud.repo);}
  async function api(path,method='GET',body){if(!token||!path.startsWith('/'))throw Error('Connect a private repository first.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(API+path,{method,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,credentials:'omit',redirect:'error',cache:'no-store',signal:controller.signal});const data=res.status===204?null:await res.json();return {status:res.status,data};}finally{clearTimeout(timer);}}
  async function verifyRepo(){const res=await api(apiPath());if(res.status!==200||res.data?.private!==true||res.data?.owner?.login?.toLowerCase()!==OWNER.toLowerCase()||res.data?.name!==DATA_REPO||cloud.user.toLowerCase()!==OWNER.toLowerCase()||!res.data.default_branch)throw Error('Sync requires your own verified private repository. Public repositories are refused.');cloud.branch=res.data.default_branch;const manifest=await readPrivate('sync-manifest.json');if(manifest.value?.kind!=='evora-progress-data-only'||manifest.value?.schema!==FORMAT)throw Error('The repository does not have the required data-only sync manifest.');return res.data;}
  function decodeContent(data){if(data?.type!=='file'||data.encoding!=='base64'||typeof data.content!=='string'||data.size>MAX_FILE)throw Error('Private file format is invalid.');const bytes=Uint8Array.from(atob(data.content.replace(/\s/g,'')),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
  const base64=s=>{const bytes=new TextEncoder().encode(s);let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(raw);};
  async function readPrivate(path){const res=await api(apiPath()+'/contents/'+path+'?ref='+encodeURIComponent(cloud.branch));if(res.status===404)return {value:null,sha:null};if(res.status!==200)throw Error('Private read failed (GitHub '+res.status+').');return {value:decodeContent(res.data),sha:res.data.sha};}
  async function loadPrivatePlan(date){const res=await readPrivate('plans/'+date+'.json');if(res.value)privatePlans[date]=validatePrivateDay(res.value,date,plan);}
  async function syncDate(date,write){if(!cloud)return;if(syncing){pending.set(date,write||pending.get(date)||false);return;}syncing=true;n['sync-now'].disabled=true;message('sync-status',write?'Private sync pending…':'Checking private saved reports…');try{await verifyRepo();await loadPrivatePlan(date);for(let attempt=0;attempt<3;attempt++){const remote=await readPrivate('progress/'+date+'.json'),remoteEntry=remote.value?parsePacket(remote.value,date):{tasks:{}},merged=mergeEntries(state.days[date]||{tasks:{}},remoteEntry);state.days[date]=merged.entry;conflicts=merged.conflicts.map(id=>({date,id}));n['resolve-conflicts'].hidden=!conflicts.length;save();if(selected===date)renderDay();if(conflicts.length)throw Error('Equal-time reports disagree. Review both devices, then explicitly resolve before uploading.');const output=packet(date,plan,state.days[date],privatePlans);if(!write||output.reported_status==='unreported'){message('sync-status',remote.value?'Private read verified. Your next change can be saved privately.':'Private connection and read verified. No remote report exists for this date; nothing was marked complete.');return;}await verifyRepo();const content=base64(JSON.stringify(output,null,2)+'\n'),body={message:'Record self-reported study progress for '+date,content,branch:cloud.branch};if(remote.sha)body.sha=remote.sha;const result=await api(apiPath()+'/contents/progress/'+date+'.json','PUT',body);if([409,422].includes(result.status)&&attempt<2)continue;if(![200,201].includes(result.status))throw Error('Private save failed (GitHub '+result.status+').');const check=await readPrivate('progress/'+date+'.json');if(!check.value||JSON.stringify(parsePacket(check.value,date))!==JSON.stringify(parsePacket(output,date)))throw Error('Private write completed but verification differed; pull again before editing.');message('sync-status','Private read and write verified for '+date+'. Telegram delivery depends on the separately configured private reminder workflow.');return;}throw Error('Concurrent changes prevented a verified save. Pull again before editing.');}catch(error){message('sync-status',(error.name==='AbortError'?'Private sync timed out.':error.message)+' Your browser report is retained. Automatic sync remains unverified.',true);}finally{syncing=false;n['sync-now'].disabled=!cloud;if(cloud&&pending.size){const [next,shouldWrite]=pending.entries().next().value;pending.delete(next);setTimeout(()=>syncDate(next,shouldWrite),0);}}}
  async function connect(){flushNote();token=n['repo-token'].value.trim();n['repo-token'].value='';const owner=n['repo-owner'].value.trim(),repo=n['repo-name'].value.trim();if(!token||!/^[a-zA-Z0-9-]{1,39}$/.test(owner)||!/^[a-zA-Z0-9_.-]{1,100}$/.test(repo)||owner.toLowerCase()!==OWNER.toLowerCase()||repo!==DATA_REPO){token='';message('sync-status','Enter a token restricted to Hostilian/EVORA-STUDY-PROGRESS. All other repository targets are refused.',true);return;}n.connect.disabled=true;try{const who=await api('/user');if(who.status!==200||typeof who.data?.login!=='string'||who.data.login.toLowerCase()!==owner.toLowerCase())throw Error('The authenticated GitHub account must own the selected private repository.');cloud={owner,repo,user:who.data.login};await verifyRepo();try{localStorage.setItem(COORDS,JSON.stringify({owner,repo}));}catch(_){}n.disconnect.disabled=false;n['sync-now'].disabled=false;await syncDate(selected,false);}catch(error){token='';cloud=null;message('sync-status',error.message+' No progress was uploaded.',true);}finally{n.connect.disabled=false;}}
  function disconnect(){clearTimeout(syncTimer);pending.clear();token='';cloud=null;n['repo-token'].value='';n.disconnect.disabled=true;n['sync-now'].disabled=true;message('sync-status','Disconnected. Token cleared from this page’s memory; your local report remains.');}
  n.connect.addEventListener('click',connect);n.disconnect.addEventListener('click',disconnect);n['sync-now'].addEventListener('click',()=>{flushNote();syncDate(selected,true);});n['resolve-conflicts'].addEventListener('click',()=>{const time=stamp();for(const c of conflicts){const e=entry(c.date);if(c.id==='day_review')e.day_review.user_reported_at=time;else e.tasks[c.id].user_reported_at=time;}conflicts=[];n['resolve-conflicts'].hidden=true;save();syncDate(selected,true);});
  n.date.addEventListener('change',()=>selectDate(n.date.value));n['previous-day'].addEventListener('click',()=>selectDate(addDays(selected,-1)));n['next-day'].addEventListener('click',()=>selectDate(addDays(selected,1)));n.today.addEventListener('click',()=>selectDate(lf.format(new Date())));n.month.addEventListener('change',renderMonth);n.note.addEventListener('input',()=>{clearTimeout(noteTimer);noteTimer=setTimeout(flushNote,350);});
  n.export.addEventListener('click',()=>{flushNote();const data={schema_version:1,format:FORMAT,exported_at:new Date().toISOString(),days:Object.fromEntries(Object.entries(state.days).map(([date,e])=>[date,packet(date,plan,e,privatePlans)]))},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=element('a');a.href=url;a.download='private-study-progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message('backup-status','Private progress file download requested. It contains no sync token.');});
  n.import.addEventListener('change',async()=>{try{const file=n.import.files?.[0];if(!file)return;if(file.size>MAX_FILE)throw Error('Choose a progress file smaller than 2 MB.');const value=JSON.parse(await file.text());if(value.format!==FORMAT||!plain(value.days))throw Error('Choose this checklist’s private progress export.');let count=0;const importedDays=Object.create(null);for(const [date,raw] of Object.entries(value.days)){if(!validDate(date))continue;const imported=parsePacket(raw,date),merged=mergeEntries(state.days[date],imported);if(merged.conflicts.length)throw Error('Equal-time imported reports disagree; keep both backups and review them before merging.');importedDays[date]=merged.entry;count++;}Object.assign(state.days,importedDays);save();renderDay();message('backup-status','Loaded '+count+' dated reports. Changed tasks retain no inherited completion tick.');queueSync();}catch(error){message('backup-status',error.message,true);}finally{n.import.value='';}});
  window.addEventListener('pagehide',()=>{flushNote();token='';});
  (async()=>{try{const res=await fetch('today-plan.json',{credentials:'omit',redirect:'error',cache:'no-cache'});if(!res.ok)throw Error('General plan could not be loaded.');plan=validatePlan(await res.json());if(queryDate&&(queryDate<plan.study_start||queryDate>plan.study_end))selected=lf.format(new Date());try{const raw=JSON.parse(localStorage.getItem(STORE)||'null');if(raw?.format===FORMAT&&plain(raw.days))for(const [date,data] of Object.entries(raw.days))if(validDate(date))state.days[date]=parsePacket(data,date);const coords=JSON.parse(localStorage.getItem(COORDS)||'null');if(plain(coords)){n['repo-owner'].value=OWNER;n['repo-name'].value=DATA_REPO;}}catch(_){message('backup-status','Some saved browser data could not be restored. Load a private backup if available.',true);}n.month.value=selected.slice(0,7);renderDay();renderMonth();renderCourseLinks();n.app.hidden=false;n['load-status'].textContent='General suggestions updated '+plan.updated_on+'. No study or official completion is inferred by opening this page.';}catch(error){message('load-status',error.message+' Open the course guide while this is unavailable.',true);}})();
})();
